version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: hotel_db
    environment:
      POSTGRES_DB: hotel_gestion
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: