spring.application.name=sistemahotelero

# Conexión a la Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_gestion
spring.datasource.username=postgres
spring.datasource.password=admin

#server.port=9090


# Configuración de Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Formato de fechas para no tener problemas con las transacciones
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
