# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
server:
  port: ${PORT:8080}
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hotel_gestion}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:adminpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
