spring.application.name=sistemahotelero

# Conexión a la Base de Datos PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_gestion
#spring.datasource.username=postgres
#spring.datasource.password=admin

# application.properties
# Configuración de PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hotel_gestion2}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:adminpassword}

spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}




# Formato de fechas para no tener problemas con las transacciones
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
