spring.application.name=sistemahotelero

# Conexión a la Base de Datos PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_gestion
#spring.datasource.username=postgres
#spring.datasource.password=admin

# application.properties
# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d852lpv7f7vs73fvvl5g-a:5432/hotel_gestion
spring.datasource.username=hotel_gestion_user
spring.datasource.password=CnQ3MN1TFO5bm8oG2cPaZlgpyepc9gSY
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}




# Formato de fechas para no tener problemas con las transacciones
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
