name: Java CI con Maven y JaCoCo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Compilar y Ejecutar Pruebas con Maven
        run: mvn clean verify

      - name: Guardar Reporte de Cobertura JaCoCo
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reporte-cobertura-jacoco
          path: target/site/jacoco/
